name: Release
description: "Creates a GitHub release and publishes targets to crates.io and NPM"
on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]
env:
  TAG_NAME: ${{ github.ref_name }}

jobs:
  # Create GitHub release
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.TAG_NAME }} \
            --verify-tag \
            --title "${{ env.TAG_NAME }}" \
            --notes "See [CHANGELOG.md](https://github.com/Daniel-Knights/changenog/blob/main/CHANGELOG.md) for details."

  # Build and publish targets
  targets:
    needs: release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      id-token: write
    env:
      EXE_NAME: changenog${{ matrix.os == 'windows-latest' && '.exe' || '' }}
      EXE_DIR: target/${{ matrix.target }}/release
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build for target
        uses: ./.github/actions/target-build
        with:
          target: ${{ matrix.target }}

      - name: Copy built executable to package directory
        run: |
          cp ${{ env.EXE_DIR }}/${{ env.EXE_NAME }} ./packages/js/targets/${{ matrix.target }}

      - name: Upload asset
        uses: ./.github/actions/upload-asset
        with:
          exe_dir: ${{ env.EXE_DIR }}
          exe_name: ${{ env.EXE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          target: ${{ matrix.target }}
          asset_path: ${{ matrix.target }}-${{ env.EXE_NAME }}

      - name: Publish target to NPM
        uses: ./.github/actions/pnpm-publish
        with:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
          package_dir: ./packages/js/targets/${{ matrix.target }}

  # Publish core to crates.io and NPM
  publish:
    needs: targets
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to crates.io
        run: cargo publish --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish core to NPM
        uses: ./.github/actions/pnpm-publish
        with:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
          package_dir: ./packages/js/core
